config/routes.rb
Rails.application.routes.draw do
  resources :products
  resources :carts
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  belongs_to :product
end

app/models/product.rb
class Product < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def update
    if Cart.all.any?
      @cart = Cart.first
    else
      @cart = Cart.create
    end
    @cart.product_id = params[:product]
    @products = @cart.product_id
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/carts/update.html.erb
My cart: <%= @products.each { |product| product.name } %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CakeCheckoutRails</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/products/index.html.erb
<% if @products.any? %>
  <%= @products.each do |product| %>
    <%= product.name %>
    <%= product.code %>
    <%= product.price %>
    <%= link_to 'Add to cart', cart_path(product), method: :put %>
  <% end %>
<% else %>
  No products in stock
<% end %>